# Iptables rules
---
iptables:
  host_allowed_udp_ports: [1984]
  host_allowed_tcp_ports: [22, 80, 443, 909]
  flush_all: True
  raw_rules:
    #- "-P INPUT DROP"
    #- "-P FORWARD DROP"
    #- "-P OUTPUT  ACCEPT"

    #- "-F"
    #- "-t nat -F"
    #- "-t mangle -F"


    - "-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment 'accept-anything-already-accepted'"
    - "-A INPUT -i lo -j ACCEPT -m comment --comment 'accept-anything-on-the-loopback-interface'"
    - "-A INPUT -m state --state INVALID -j DROP -m comment --comment 'drop-invalid-packets'"

    - "-A INPUT -p udp --dport  500 -j ACCEPT -m comment --comment 'accept-IPSec/NAT-T-for-VPN'"
    - "-A INPUT -p udp --dport 4500 -j ACCEPT -m comment --comment 'accept-IPSec/NAT-T-for-VPN'"
    - "-A FORWARD --match policy --pol ipsec --dir in  --proto esp -s {{ ipsec_vpn_network }} -j ACCEPT -m comment --comment 'forward-VPN-traffic-anywhere'"
    - "-A FORWARD --match policy --pol ipsec --dir out --proto esp -d {{ ipsec_vpn_network }} -j ACCEPT -m comment --comment 'forward-VPN-traffic-anywhere'"
    - "-t mangle -A FORWARD --match policy --pol ipsec --dir in -s {{ ipsec_vpn_network }} -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360 -m comment --comment 'reduce-MTU/MSS-values-for-dumb-VPN-clients'"
    - "-t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -m policy --pol ipsec --dir out -j ACCEPT -m comment --comment 'exempt-IPsec-traffic-from-masquerading'"
    - "-t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -j MASQUERADE -m comment --comment 'masquerade-VPN-traffic-over-eth0-etc'"
      #- "-A INPUT   -j DROP -m comment --comment 'fall-through-to-drop-any-other-input-traffic'"
      #- "-A FORWARD -j DROP -m comment --comment 'fall-through-to-drop-any-other-forward-traffic'"

