---
# OpenVPN settings
server_port: 1494
protocol: tcp
server_name: ruvpn.rusty.host
topology: subnet
client_config_dir_path: /etc/openvpn/ccd
persist_tun: True
persist_key: True
dev_type: tun
allow_masquerade: True
use_tls_auth: True
additional_pushes:
 - "redirect-gateway def1"
real_server_name: ruvpn.rusty.host
vpn_network: 10.20.0.0
vpn_netmask: 255.255.255.0
vpn_cidr: 24
dns_pushes:
  - 8.8.8.8
  - 8.8.4.4
ping: 5
ping_restart: 30
comp_lzo: False
auth: SHA512
cipher: AES-256-CBC
syslog_name: openvpn
cert_prefix: "ruvds"
# What to do with given client name. Valid values: issue, revoke
keys_action: issue
duplicate_cn: True
client_to_client: True
iptables_configure: True
use_ldap: False
clients: "{{ vault_clients }}"
